# Blog settings
permalink: /blog/:title


# My variables
name: Stewart Henderson
description: Software engineer
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Analytics
analytics :
  provider : google
  google : 
    tracking_id : 'UA-51497840-1'
  getclicky :
site_id : '100854903'
highlighter: pygments
gems:
  - jekyll-gist
  - pygments.rb
