# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]
pygments:         true

# Permalinks
permalink: /blog/:year/:month/:day/

# Setup
title:            Bowl of Stew
tagline:          'Software developer'
url:              http://bowlofstew.github.io
shorturl:         bowlofstew.github.io
paginate:         5
author:
  name:           Stewart Henderson
  url:            https://twitter.com/__shenderson__
  email:          henderson.geoffrey@gmail.com

github:
  repo:           github.com/bowlofstew/bowlofstew.github.io

version:          1.0.2

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
