# Site wide configuration

title: Bowl Of Stew
description:
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://bowlofstew.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap

analytics :
  provider : google
  google : 
    tracking_id : 'UA-51497840-1'
  getclicky :
    site_id : '100854903'

# Site owner
owner:
  name: Stewart Henderson
  email: henderson.geoffrey@gmail.com
  twitter: __shenderson__
  google:
    ad-client: 'ca-pub-4593390900259285'
    ad-slot: '9691101052'
  bio: 
  avatar: me.jpg # 160x160 px image for author byline
disqus-shortname: bowlofstewgithub


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
